### ISSUE TITLE
New feature: Add a Setting to the Block so that an editing teacher can configure who is allowed to Exchange items with other users

### ISSUE THREAD

**Issue by andreasschenkel** [abgreeve/moodle-block_stash#16]
In some cases a teacher does not want the students to be able to share or exchange items with other users. So a setting to enable or disable sharing/exchanging might be an interesting feature.

**Comment by abgreeve** [comment]
Hello Andreas, This is available. If you enable editing for the course and then click the edit icon on the block, there is a setting to disable user trading.
Can you please let me know if you find the setting?

**Comment by andreasschenkel** [comment]
Great!!!!! Not easy to find, but it works as accepted. Thank you.
