### ISSUE TITLE
Tradecenter: Clicking on item select dropdown fails with console error

### ISSUE THREAD

**Issue by PhMemmel** [abgreeve/moodle-block_stash#18]
Going to the tradecenter and clicking "select an item" fails with a console error.

Further debugging shows that this is due to a "non existing database" table, because of a hard coded database prefix in `classes/swap_handler.php` in method `get_swappable_items()`.

**Comment by abgreeve** [comment]
Great catch. I've created a fix and I'll include this in the next release.
