### ISSUE TITLE
Error adding block to course categories

### ISSUE THREAD

**Issue by FMCorz** [abgreeve/moodle-block_stash#21]
> Dear developer,
> 
> thanks for your great gamification plugin.
> 
> One tiny issue: It should not be possible for users to add stash blocks to course categories. This leads to an error that makes it impossible to use the concerning category unless the conflicting database entry is deleted.
> 
> Best regards
> Andreas

Originally reported here: https://github.com/FMCorz/moodle-block_stash/issues/26

**Comment by abgreeve** [comment]
Thank Fred, I'll go and take a look. I don't imagine that it should be too difficult to fix.

**Comment by abgreeve** [comment]
Fixed in the most recent release.
